name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: '0 */12 * * *' # runs every 12 hours
  workflow_dispatch:      # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install snk

      - name: Generate snake
        run: |
          mkdir -p output
          snk --username YoussefElshafei --color "#006400" --output output/github-contribution-grid-snake.svg

      - name: Commit and push snake
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update GitHub Contribution Snake" || echo "No changes to commit"
          git push

